print("=======STUDENT PROFILE=======")
name=input("Name:")
age=int(input("Age:"))
college=input("College:")
favorite_technology=input("Favorite Technology:")
print("NAME:",name)
print("AGE:",age)
print("COLLEGE:",college)
print("FAVORITE TECHNOLOGY:",favorite_technology)
